name: paginate_firestore
description: A flutter package to simplify pagination with firestore data.
version: 1.0.3+1
homepage: https://github.com/excogitatr/paginate_firestore
issue_tracker: https://github.com/excogitatr/paginate_firestore/issues

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^9.2.0
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
